### ISSUE TITLE
How do you get your data?

### ISSUE THREAD

**Issue by kwcorco** [wakkatu/dhero#3]
Really curious how you retrieve the data for each hero? Is it just a manual calculation on your part?

**Comment by kwcorco** [comment]
Scatch this question. New one lol: how have you managed to extract the hero images from the .etc2 file?

**Comment by wakkatu** [comment]
You can decode .etc1/.etc2 to .tga by ETCPACK and split it by ImageMagick according to .altas.

**Comment by jjwbigtoe** [comment]
How are the variable values calculated? Like Basic Damage at different color levels?

**Comment by jjwbigtoe** [comment]
> Really curious how you retrieve the data for each hero? Is it just a manual calculation on your part?


How are they calculated?

**Comment by wakkatu** [comment]
You can see all the formulas in the source of web pages.

For example, basic damage can be calculated as below
1. find `name="core_basic_damage"` => `data-formula="38.5 + 10.175g"`
2. find `name="g"` => `data-formula="v*r*(1+s)/2"`
3. repeat to find all operands to calculate `core_basic_damage`
